### ISSUE TITLE
multi-hop-locks: error[E0308]: mismatched types 

### ISSUE THREAD

**Issue by susil-mohanty** [KZen-networks/multi-hop-locks#6]
While running $cargo test, I am getting the bellow errors, What are the issues here?
mismatched types
$ cargo test
    Updating git repository `https://github.com/KZen-networks/rust-gmp`
    Updating git repository `https://github.com/KZen-networks/curv`
    Updating crates.io index
    Updating git repository `https://github.com/KZen-networks/multi-party-ecdsa`
    Updating git repository `https://github.com/KZen-networks/rust-paillier`
    Updating git repository `https://github.com/KZen-networks/zk-paillier`
    Updating git repository `https://github.com/KZen-networks/centipede`
    Updating git repository `https://github.com/KZen-networks/rust-paillier`
    Updating git repository `https://github.com/KZen-networks/zk-paillier`
    Updating git repository `https://github.com/KZen-networks/bulletproofs`
   Compiling multi-hop-locks v0.1.0 (/home/nslab/Documents/multi-hop-locks)
error[E0308]: mismatched types
  --> src/tests.rs:74:17
   |
74 |                 &ek,
   |                 ^^^ expected struct `paillier::EncryptionKey`, found a different struct `paillier::EncryptionKey`
   |
   = note: expected type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
              found type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
note: Perhaps two different versions of crate `paillier` are being used?
  --> src/tests.rs:74:17
   |
74 |                 &ek,
   |                 ^^^

error[E0308]: mismatched types
  --> src/tests.rs:75:17
   |
75 |                 &dk,
   |                 ^^^ expected struct `paillier::DecryptionKey`, found a different struct `paillier::DecryptionKey`
   |
   = note: expected type `&paillier::DecryptionKey` (struct `paillier::DecryptionKey`)
              found type `&paillier::DecryptionKey` (struct `paillier::DecryptionKey`)
note: Perhaps two different versions of crate `paillier` are being used?
  --> src/tests.rs:75:17
   |
75 |                 &dk,
   |                 ^^^

error[E0308]: mismatched types
   --> src/tests.rs:159:13
    |
159 |             &party_two_paillier.ek,
    |             ^^^^^^^^^^^^^^^^^^^^^^ expected struct `paillier::EncryptionKey`, found a different struct `paillier::EncryptionKey`
    |
    = note: expected type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
               found type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
note: Perhaps two different versions of crate `paillier` are being used?
   --> src/tests.rs:159:13
    |
159 |             &party_two_paillier.ek,
    |             ^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/tests.rs:220:17
    |
220 |                 &ek,
    |                 ^^^ expected struct `paillier::EncryptionKey`, found a different struct `paillier::EncryptionKey`
    |
    = note: expected type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
               found type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
note: Perhaps two different versions of crate `paillier` are being used?
   --> src/tests.rs:220:17
    |
220 |                 &ek,
    |                 ^^^

error[E0308]: mismatched types
   --> src/tests.rs:221:17
    |
221 |                 &dk,
    |                 ^^^ expected struct `paillier::DecryptionKey`, found a different struct `paillier::DecryptionKey`
    |
    = note: expected type `&paillier::DecryptionKey` (struct `paillier::DecryptionKey`)
               found type `&paillier::DecryptionKey` (struct `paillier::DecryptionKey`)
note: Perhaps two different versions of crate `paillier` are being used?
   --> src/tests.rs:221:17
    |
221 |                 &dk,
    |                 ^^^

error[E0308]: mismatched types
   --> src/tests.rs:281:13
    |
281 |             &party_two_paillier.ek,
    |             ^^^^^^^^^^^^^^^^^^^^^^ expected struct `paillier::EncryptionKey`, found a different struct `paillier::EncryptionKey`
    |
    = note: expected type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
               found type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
note: Perhaps two different versions of crate `paillier` are being used?
   --> src/tests.rs:281:13
    |
281 |             &party_two_paillier.ek,
    |             ^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/tests.rs:328:13
    |
328 |             &party_two_paillier.ek,
    |             ^^^^^^^^^^^^^^^^^^^^^^ expected struct `paillier::EncryptionKey`, found a different struct `paillier::EncryptionKey`
    |
    = note: expected type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
               found type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
note: Perhaps two different versions of crate `paillier` are being used?
   --> src/tests.rs:328:13
    |
328 |             &party_two_paillier.ek,
    |             ^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/tests.rs:375:13
    |
375 |             &party_two_paillier.ek,
    |             ^^^^^^^^^^^^^^^^^^^^^^ expected struct `paillier::EncryptionKey`, found a different struct `paillier::EncryptionKey`
    |
    = note: expected type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
               found type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
note: Perhaps two different versions of crate `paillier` are being used?
   --> src/tests.rs:375:13
    |
375 |             &party_two_paillier.ek,
    |             ^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/tests.rs:422:13
    |
422 |             &party_two_paillier.ek,
    |             ^^^^^^^^^^^^^^^^^^^^^^ expected struct `paillier::EncryptionKey`, found a different struct `paillier::EncryptionKey`
    |
    = note: expected type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
               found type `&paillier::EncryptionKey` (struct `paillier::EncryptionKey`)
note: Perhaps two different versions of crate `paillier` are being used?
   --> src/tests.rs:422:13
    |
422 |             &party_two_paillier.ek,
    |             ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 9 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `multi-hop-locks`.

To learn more, run the command again with --verbose.

**Comment by omershlo** [comment]
Hey, sorry about that. It is now fixed (please double check!)
Issue was that we tags were not consistent. Thank you!

**Comment by susil-mohanty** [comment]
Thank you for your quick action. It's a great help to me.
